### ISSUE TITLE
Error get-pip.py install Ubuntu 18/20

### ISSUE THREAD

**Issue by geethupendra** [pypa/get-pip#90] opened 2021-01-26 16:02 UTC
Hello,

I have an issue with install pip on Ubuntu 18.04 / Ubuntu 20.04, any solution for sort this..

root@ip-xxxx:~# curl https://bootstrap.pypa.io/get-pip.py | python
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1883k  100 1883k    0     0  12.6M      0 --:--:-- --:--:-- --:--:-- 12.5M
Traceback (most recent call last):
  File "<stdin>", line 24226, in <module>
  File "<stdin>", line 199, in main
  File "<stdin>", line 82, in bootstrap
  File "/tmp/tmpSKr2ps/pip.zip/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax

Thanks
Geeth

**Comment by webknjaz** [comment] 2021-01-26 16:07
Duplicate of https://github.com/pypa/get-pip/issues/89

**Closed by webknjaz** 2021-01-26 16:07 UTC

**Comment by webknjaz** [comment] 2021-01-26 16:08
As outlined @ https://github.com/pypa/get-pip/issues/82#issuecomment-766147026, please use a URL matching your Python version, like https://bootstrap.pypa.io/2.7/get-pip.py.
