### ISSUE TITLE
Add tags

### ISSUE THREAD

**Issue by Czaki** [pypa/get-pip#56] opened 2020-01-20 11:34 UTC
If it is possible to add tags for get_pip releases? Currently, if there is need to get deterministic build (continuous integration) the there is need to pin with commit hash which is unreadable for human.

**Comment by lobsterdore** [comment] 2020-01-21 15:08
I second this, after towards outage I think we need a guaranteed way to get older versions of pip, tagging get-pip for the version that it comes bundled with would be great.

**Comment by Flamefire** [comment] 2020-02-26 10:01
Yes please. Having releases with a known SHA-256 of get-pip.py (the final version) would be great for security and reproducibility.

**Comment by pradyunsg** [comment] 2020-04-28 17:03
> If it is possible to add tags for get_pip releases?

I've gone ahead and done this for pip 20.1 (released just now). I don't want to go back and tag existing releases, and we'd likely need to want to add automation for these releases TBH.

**Comment by pradyunsg** [comment] 2021-01-24 09:36
Closing since we've added these for recent releases, and I don't think we should be back-filling here.

**Closed by pradyunsg** 2021-01-24 09:36 UTC
