### ISSUE TITLE
main.py error

### ISSUE THREAD

**Issue by geethupendra** [pypa/get-pip#89] opened 2021-01-26 12:51 UTC
Hello,

I just try yo install pip to Ubuntu 20.04 / Ubuntu 18.04 getting an error,
any anyone sorted..?  Server Location :  AWS

root@ip-xxxx:~# curl https://bootstrap.pypa.io/get-pip.py | python
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1883k  100 1883k    0     0  27.8M      0 --:--:-- --:--:-- --:--:-- 27.4M
Traceback (most recent call last):
  File "<stdin>", line 24226, in <module>
  File "<stdin>", line 199, in main
  File "<stdin>", line 82, in bootstrap
  File "/tmp/tmp2vWswC/pip.zip/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^

Thanks
geeth

**Comment by webknjaz** [comment] 2021-01-26 13:13
Duplicate of https://github.com/pypa/get-pip/issues/82

**Closed by webknjaz** 2021-01-26 13:13 UTC
