### ISSUE TITLE
python 3.6 embed cannot get pip

### ISSUE THREAD

**Issue by cprogrammer1994** [pypa/get-pip#7] opened 2016-12-29 17:14 UTC
Downloaded python 3.6 embeddable zip file (windows 32 bit)

Downloaded get-pip.py from the following URL:
https://pip.pypa.io/en/stable/installing/

This is the traceback:
```
Traceback (most recent call last):
  File "get-pip.py", line 20061, in <module>
    main()
  File "get-pip.py", line 194, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 82, in bootstrap
    import pip
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\User\AppData\Local\Temp\tmpinoq60hn\pip.zip\pip\__init__.py", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\User\AppData\Local\Temp\tmpinoq60hn\pip.zip\pip\utils\__init__.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\User\AppData\Local\Temp\tmpinoq60hn\pip.zip\pip\locations.py", line 88, in <module>
  File "ntpath.py", line 75, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by magnusjjj** [comment] 2017-01-23 10:09
Have started debugging this, and it seems like get-pip tries to find the 'user site', gets nothing, panics.

This can be reproduced via python -m site --user-site

**Comment by cprogrammer1994** [comment] 2017-01-23 10:40
your post made me find the solution :D

The file *python36._pth* will load the site module and run `site.main()` automatically before any other python code.

So the only thing to solve this issue is to uncomment the line in the *python36._pth*

```
python36.zip
.

# Uncomment to run site.main() automatically
import site
```

Running *get-pip.py*:

```
Collecting pip
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 445kB/s
Collecting setuptools
  Downloading setuptools-33.1.1-py2.py3-none-any.whl (472kB)
    100% |████████████████████████████████| 481kB 810kB/s
Collecting wheel
  Downloading wheel-0.29.0-py2.py3-none-any.whl (66kB)
    100% |████████████████████████████████| 71kB 926kB/s
Installing collected packages: pip, setuptools, wheel
Successfully installed pip-9.0.1 setuptools-33.1.1 wheel-0.29.0
```

**Comment by magnusjjj** [comment] 2017-01-23 10:40
added

import site

print(site.getuserbase())
print(site.getusersitepackages())

to the start of get-pip.py , and created a directory called Python36/site-packages

that.. at least installed it. Now for some testing :).

**Comment by magnusjjj** [comment] 2017-01-23 10:40
lol, you got there first :D

**Comment by cprogrammer1994** [comment] 2017-01-23 10:42
lets PR a change for checking `sys.path` if the sites are loaded before running get-pip.py

**Comment by cprogrammer1994** [comment] 2017-01-23 10:49
adding

```
import site
site.main()
```

after the imports will solve the errors from **get-pip.py** but you won't be able to use the modules using `python -m ...`

What if a custom error may show the user what he should do with the **python36._pth** file?

**Comment by magnusjjj** [comment] 2017-01-23 10:52
Yeah, sounds good. A try/except there should be pretty damn handy. You wanna grab it or should I? :).

**Comment by cprogrammer1994** [comment] 2017-01-23 11:04
https://github.com/pypa/get-pip/pull/9

what do you think an exception would be better?

**Comment by gnbl** [comment] 2017-04-26 12:01
Same issue: https://github.com/pypa/pip/issues/4207

**Comment by auzadventure** [comment] 2017-06-14 11:54
Yes, I uncommented the line in python36._pth
import site 

Seemed to work, testing now

**Comment by ali-suleiman-44b20b39** [comment] 2018-03-16 16:59
Thank you so much! =)

**Comment by ljgww** [comment] 2018-06-29 21:18
I believe I made it working on win7. A bit of hackity-hack (copying files to site packages + enabling this or that - as above). At the end I could work with the bundle + some external libs.
I understand Python people are reluctant to give python+vendor as 'embedded' but for internal use I believe it works just fine.

**Comment by pradyunsg** [comment] 2019-09-19 15:16
I'm gonna close this, since the underlying issue has been discussed and a resolution reached on pypa/pip#4207. Thanks for the discussion on this everyone! ^>^

**Closed by pradyunsg** 2019-09-19 15:16 UTC
Labels: question
