### ISSUE TITLE
Validating the authenticity of get-pip.py

### ISSUE THREAD

**Issue by mcpate** [pypa/get-pip#206] opened 2024-03-05 22:29 UTC
Hey team/community! Is there a recommended way to validate the integrity of get-pip.py? I've downloaded and am planning on using https://bootstrap.pypa.io/pip/2.7/get-pip.py, and I'd love to validate the authenticity of the file I've downloaded, but I don't see any way to do so (signing keys, SHAs, etc.). Any suggestions you can provide would be greatly appreciated.

**Comment by pradyunsg** [comment] 2024-03-06 09:17
Duplicate of #41 and #47

**Closed by pradyunsg** 2024-03-06 09:17 UTC

**Comment by mcpate** [comment] 2024-03-06 13:40
Apologies. Thank you!
