### ISSUE TITLE
Pip fails to install into clean virtualenv.

### ISSUE THREAD

**Issue by fake-name** [pypa/get-pip#20] opened 2018-04-15 01:43 UTC
This happened approximately 12 hours ago.

I have a deploy script which has the following snippet:

```
python3 -m venv --without-pip venv
wget https://bootstrap.pypa.io/get-pip.py
./venv/bin/python3 get-pip.py
./venv/bin/pip install six
```

Prior to 12 hours ago, this worked.

Currently, this fails on `./venv/bin/pip install six`, because `./venv/bin/python3 get-pip.py` no longer results in the `./venv/bin/pip` file being created.

Sourcing the venv prior to installing pip also fails to result in a proper install.

I can reproduce this reliably.

Platform: Ubuntu 14.04 LTS, Python 3.4.3.

**Comment by fake-name** [comment] 2018-04-15 01:52
Ok, running it with `./venv/bin/python3 get-pip.py --force-reinstall` fixes the issue.

Apparently:

 1. Pip/get-pip/something is caching state outside of the virtualenv, because I completely blew away `/tmp` and `./venv` and retried, and it didn't fix the issue.
 2. This appears to also be https://github.com/pypa/pip/issues/5220

**Comment by alex** [comment] 2018-04-15 01:53
This is a dupe of #19 and can be closed.

**Comment by fake-name** [comment] 2018-04-15 01:54
Heh.

**Closed by alex** 2018-04-15 01:53 UTC
